### ISSUE TITLE
Unsatisfying arithmetic sequences e.g. `[0 .. n - 1]`

### ISSUE THREAD

**Issue by chreekat** [lspitzner/brittany#104]
I'm not really sure what the best practice for the various cases are. These seems pretty reasonable:

```haskell
-- 👍 
[1..8]
[0..]
```

I am less certain about more complex expressions. I personally just remove all whitespace within arithmetic sequences, but I don't feel particularly good about it:

```haskell
-- ???
[0..n-1]
```

But like the title says, this is pretty unsatisfying:

```haskell
-- 👎
[0 .. n - 1]
```

Have you put any thought into the possibilities here?

**Comment by tfausak** [comment]
For what it's worth, I like how Brittany currently formats these. I prefer putting spaces around operators, and I consider `..` to be an operator of sorts.

**Comment by chreekat** [comment]
@tfausak I can't really argue. I put spaces around operators, in general. I guess I just got used to seeing no spaces in most of the examples I come across.

**Comment by eborden** [comment]
Yeah, I'm with @tfausak on this one. I like the way `brittany` is currently formatting.

**Comment by lspitzner** [comment]
Reminds me of #67 (spaces used in sections). More generally, it is again the decision between "shorter" and "more consistent". There are two reasons for brittany sticking to the "consistency" route currently:

1) It is easier to implement. `[0..n-1]` would be surprisingly hard to implement, because the layouting of expressions now would be "context sensitive". The simpler cases would still need special-case handling (e.g. if we wanted `[literal..literal]` but otherwise `[expr .. expr]`).
2) Consistency is good for readability, and the two spaces you gain here are not really worth it.

The though process is
- `n-1` vs `n - 1` - use latter because no context sensitive layouting for exprs
- `[0..n - 1]` vs `[0 .. n - 1]` - use latter because former is confusing space-precedence-implication-wise.
- `[0..10]` vs `[0 .. 10]` - use latter because more consistent with `[0 .. n - 1]`

Is that convincing enough? :) I know in both cases there is a lot of code out there that omits the spaces for certain cases, e.g. for sections `(x:)` or `(20*)`, and here `[1..]` or `[a..b]`. And I still do write `[1..10]`  myself. But I think the current behaviour is the "correct" one.

**Comment by chreekat** [comment]
Thanks for taking the time to list your rationale so clearly! My "issue" is resolved.

**Comment by codygman** [comment]
FWIW our brittany update just changed `[0..5]` to `[0 .. 5]` and to throw my opinion out there:

I dislike it.

I imagine that doesn't mean a lot, but I felt compelled enough to track down this relevant issue and comment this :sweat_smile:
