### ISSUE TITLE
More graceful error handling

### ISSUE THREAD

**Issue by ElvishJerricco** [lspitzner/brittany#11]
I've opened two issues today about GHC features that Brittany doesn't support. When encountered, Brittany will error. Would it be possible to handle these cases more gracefully? Perhaps by simply ignoring them and giving back the original source for that line / code block?

**Comment by lspitzner** [comment]
In general inserting the original source is problematic because it can create syntactically invalid code (imagine inside a do-block; brittany layouts it with more indentation; original source contains newlines with little indentation).

But I agree this can be improved; since brittany checks the output for synt. validity the user will get that error instead in the worst case. And for simple one-line cases it is unproblematic anyways. I have started implementing this, will finish in the next days.

**Comment by lspitzner** [comment]
I noticed that, at least in theory, there can be cases where the syntactic validity check is not sufficient - if you are really unlucky, the exactprinted (i.e. original) source code may is valid haskell, syntactically and even semantically, but with different semantics than pre-transformation. I have not really explored which constructs would allow for that, but I'd rather be safe.
For that reason I have now added a flag, that defaults to "only use the original if it does not contain newlines" but otherwise error. If you want the theoretically risky behaviour, you can change your config to that behaviour as well.

There might be ways to make this safer, e.g. by inserting parentheses, but I don't want to spend too much time on this; it is all just a temporary fix until somebody finds time to implement all the syntactical constructs that brittany does not handle yet.
