### ISSUE TITLE
Installation instruction is wrong

### ISSUE THREAD

**Issue by hasufell** [lspitzner/brittany#154]
```sh
$ cp `./find dist-newstyle/build/ -type f -name brittany` $HOME/.cabal/bin/
bash: ./find: No such file or directory
cp: missing destination file operand after '/home/jule/.cabal/bin/'
Try 'cp --help' for more information.
```

You probably meant

```sh
$ cp `find dist-newstyle/build/ -type f -name brittany` $HOME/.cabal/bin/
```

**Comment by lspitzner** [comment]
Right, thanks for the report. Fixed in b37732d658278e4c3a2495dcc5f25f13e20de1fd. I also included some "use latest file found" bits (that probably only is necessary if you install with a different ghc version without cleaning in between - there is a risk that you end up copying an older artefact otherwise).
