### ISSUE TITLE
State of Brittany

### ISSUE THREAD

**Issue by symbiont-joseph-kachmar** [lspitzner/brittany#229]
Sort of a "meta-issue" rather than a direct issue, but what's the current state of this project?

I'm looking at moving away from `stylish-haskell` and `hindent` and Brittany seemed like it would be the logical choice, but it looks like activity's kind of slowed down on the repo (e.g. last commit was 6 months ago, issues haven't been responded to, open PRs unmerged and without comment, etc.).

Is there anything that volunteers could do to help with Brittany's active development and maintenance on these fronts?

**Comment by tfausak** [comment]
@lspitzner invited me to be a collaborator to this repository more than a year ago. I don't have the bandwidth to contribute changes to this project, but I do have both the time and ability to maintain it by triaging issues and merging PRs. I haven't done so yet because (a) I wasn't given explicit permission to do that, and (b) I wouldn't be able to push changes to Hackage anyway. 

Because Lennart has been absent for so long, it makes sense to try and move things forward without him. I could manage this repo (or use my fork for now) and ping the Hackage trustees to get maintainership on there (or publish my own fork).

I've sent Lennart an email pointing to this issue just in case he's got GitHub notifications disabled.

**Comment by eborden** [comment]
@tfausak I sent @lspitzner an email a ways back. I have yet to hear from him. Hopefully everything is okay.

I'd be happy to help share some of the burden.

**Comment by tfausak** [comment]
Looks like there was a flurry of activity earlier this week. Lennart merged a bunch of pull requests.

**Comment by lspitzner** [comment]
@symbiont-joseph-kachmar @eborden @tfausak and everyone else, sorry for being silent for so long. I am indeed working on catching up on stuff, and there is more good news below.

I have reduced my participation in the haskell community at large both due to a lack of time/personal reasons and due to be being mildly discontent with certain communication styles and leadership in this community. (Leaving the last point that vague is not ideal, but I neither want to omit it entirely nor do I want to give it too much weight. I may expand at some point, as long as I manage to keep it constructive, which is hard.)

But I have not stopped using haskell, and am still using brittany. I also should stress that the above does not include the communication style of contribution/discussions around brittany - I don't want to judge my own style, but I think all contributions to this project from others have been friendly and constructive.

Recent and future changes:

- I am getting sponsored to work on brittany (yay!) (details will follow) (and no worries, all will remain under the existing open license);
- To prevent any hold-ups, I will set myself some rules that mostly boil down to "make more releases, don't block on any planned features or management-decisions";
- This hopefully is not necessary in the near future, but to prevent this project from stalling like it did until now, should I become unavailable for whatever reason in the future, I will give github/hackage/stackage rights as appropriate to co-maintainers (I have @tfausak and @eborden in mind. I am open to further applications.)
- I will also make it possible to donate to the project. I don't expect any large sums, and some work is getting sponsored already, but both as a thanks to the past work, keeping the online service at hexagoxel.de/brittany running, and if you want to motivate me to spend time on some particular issue on the weekend.

I realize that my effective absence has unnecessarily cost some time for a good amount of users (getting brittany to work without stackage, writing their own bug-fixes around stuff etc.) and while I reject any guilt (you ~~are~~ have been getting this for free!) I am sorry for this situation and I will work on improving some non-ideal aspects to my maintainer-role.

Thank you for your patience, see you soon (and someone please implement a timer that says "time spend re-reading what you have written while hovering over the "comment" button :D)

-- hexagoxel

**Comment by lspitzner** [comment]
Before I close this: Anyone opposed to releasing a new version off of current master? The recent merges might be untested, and at least one of them is a layouting change not behind a new config flag (i.e., behaviour changes without the user actively opting-in via a config flag), but then this is exactly the kind of blocking that I want to reduce.

(This "layouting stability" idea (no behaviour changes without opt-in between minor versions) is on the agenda for 1.0 though. But until then, ship it?)

**Comment by tfausak** [comment]
Happy to have you back, @lspitzner! 

> Anyone opposed to releasing a new version off of current master? 

I would like that very much!

**Comment by eborden** [comment]
@lspitzner thanks for the update. Glad to have you back and I hope you've been able to rest and recharge. Feel free to lean on me if you are feeling overwhelmed or need to vent.

> Anyone opposed to releasing a new version off of current master?

:shipit:

**Comment by tfausak** [comment]
- #235 covers layouting stability.
- A new release should be coming out Soon ™️.
- I'm working on putting together a roadmap here on GitHub using @lspitzner's notes.

**Comment by lspitzner** [comment]
[brittany-0.12.0.0](https://hackage.haskell.org/package/brittany-0.12.0.0) is out.

**Comment by tfausak** [comment]
And the roadmap to 1.0.0.0 is available here on GitHub as a milestone: https://github.com/lspitzner/brittany/milestone/1

**Comment by expipiplus1** [comment]
> will also make it possible to donate to the project

Github sponsors is out of beta now, perhaps it's possible to get that no doubt lucrative button at the top of this repo.
