### ISSUE TITLE
Support for GHC 8.8.1

### ISSUE THREAD

**Issue by InBetweenNames** [lspitzner/brittany#255]
GHC 8.8.1 is out now -- any idea how to get brittany built with it?  It seems some internals might have changed.

**Comment by lspitzner** [comment]
ghc-8.8 support should be ready; I pushed the necessary changes to the `travis` branch (for now). Although it won't do you any good because there are several dependencies that don't (officially) support ghc-8.8 yet. And once they update, we might have to bump our version bounds. With some luck that will be dep-bound only changes though.

The ghc-8.8 version of ghc-exactprint caused one change to brittany behaviour: Parentheses might be "normalised" (i.e. removed when they are not required) in a couple of places, where previously we retained the input parens. An example (that caused problems in ghc-8.8) are type synonyms: Previously `type (MyType a) = Maybe a` roundtripped as-is, while now it is normalized to `type MyType a = Maybe a`.

**Comment by InBetweenNames** [comment]
Thank you!

**Comment by lspitzner** [comment]
This is fixed with `brittany-0.12.1.0`
