### ISSUE TITLE
Release current master?

### ISSUE THREAD

**Issue by andys8** [lspitzner/brittany#318]
Hi :)

I noticed there are features and bugfixes on `master` that aren't released.

https://github.com/lspitzner/brittany/compare/0.12.1.1.x2...master

* formatting `data`
* `module .. where`
* support for pattern synonyms

If https://github.com/lspitzner/brittany/issues/47 isn't partially implemented and could lead to issues, one could consider releasing the current state as is. I ran it on a code base and the changes it produces seem to improve things (mainly because `data` is formatted).

**Comment by tfausak** [comment]
I technically have permission to do this, but I haven't done it before and I don't know the exact process.

:pager: @lspitzner @eborden

**Comment by arybczak** [comment]
Seconded. Can we please get a release with #312 merged?

**Comment by vaclavsvejcar** [comment]
It would be really awesome. As a workaround I ended up building own versions from master.

**Comment by maralorn** [comment]
I‘d like to emphasize the need for this. Recent releases of haskell-language-server are not compatible with the last released brittany version. (at least I think so, because they switched to using @bubba's branch). And there are plans to release hls to hackage soon.

Making a small minor release of brittany would be great to help with packaging hls downstream. (i.e. right now we maintain two different brittanies in nixpkgs.)

**Comment by expipiplus1** [comment]
@tfausak I think you should just bite the bullet and go ahead, what's the worst that can happen, a version has to be marked deprecated on Hackage?

**Comment by arybczak** [comment]
Indeed, perfectionism leads to inaction. Please release the master + #312 :pray:

**Comment by tfausak** [comment]
I have built and released the current master branch as version 0.12.2.0.

- https://hackage.haskell.org/package/brittany-0.12.2.0
- https://github.com/lspitzner/brittany/releases/tag/0.12.2.0 (includes binaries)

I didn't merge #312 because the build failed with GHC < 8.8 and the tests failed with GHC 8.10. If you'd like to help, please see  #324. 

I didn't update the demo site (https://hexagoxel.de/brittany/) because I don't know how.

**Comment by expipiplus1** [comment]
Thanks!
