### ISSUE TITLE
Enable common syntactic extensions by default

### ISSUE THREAD

**Issue by wz1000** [lspitzner/brittany#32]
Brittany often fails to parse fragments of files due to the usage of GHC extensions. I propose enabling common syntactic extensions like LambdaCase, ExplicitForall, TupleSections, TypeApplications etc. by default to handle this.

**Comment by lspitzner** [comment]
Ah yes, my `brittany.yaml` contains

~~~~
conf_forward:
  options_ghc:
  - -XLambdaCase
  - -XMultiWayIf
  - -XGADTs
  - -XPatternGuards
  - -XViewPatterns
  - -XTupleSections
  - -XExplicitForAll
  - -XImplicitParams
  - -XQuasiQuotes
  - -XTemplateHaskell
  - -XBangPatterns
~~~~

but those are not there by default. I'm reluctant to add those to the `staticDefaultConfig` because then the user could not disable them anymore; however it'd be trivial to create and expose a `ForwardOptions` value containing these and use that by default in the hie-plugin, at least until more fine-grained configuration is supported.

(Also, perhaps the initial config file _should_ contain these even if the `staticDefaultConfig` does not.. maybe my design is insufficient (because merging different configs never can delete items in that list currently), or maybe "default" depends on context - i'll have to think about this.)

(Also, note to self: there is an GADTSyntax extension only, right? Might be better than full GADTs; not that it matters too much.)

I'll implement the the mentioned `ForwardOptions` value in the next days.

**Comment by ElvishJerricco** [comment]
I don't think there should be extensions on by default. I think Brittany should offer an interface for formatting just a region of a file, so that it can use the whole file to see what extensions it needs, but only change the region the user wants.

**Comment by lspitzner** [comment]
On the other hand, disabling syntactic extensions might not be necessary at all, unless.. are there cases where these extensions reject programs that are previously accepted? If not, the worst case is that brittany does not error on "invalid" input, but checking validity is not really brittany's job.

**Comment by lspitzner** [comment]
@ElvishJerricco extensions can in general be defined not only via pragma, but also via cabal's default-extension and probably via stack somehow too. but i somewhat agree: the library interface already supports enabling extensions via the config, and the rest perhaps is the plugin's job.

Nonetheless I see that where I can use the `brittany.yaml` to define global defaults for the executable, doing the same for the hie-workflow is a bit more tricky. And there is no harm in exposing an additional alternative-default-(sub-)config in the library interface.

**Comment by lspitzner** [comment]
I have added the sub-config value in 5a82968a7b361a939185b9c05d7e5d9558892fb4 and created [a PR over at haskell-ide-engine](https://github.com/alanz/haskell-ide-engine/pull/1).

**Comment by lspitzner** [comment]
And sorry it took so long for such a simple change..

**Comment by alanz** [comment]
Thanks.

Thinking about it, in the hie scenario we generally have a project and are doing GHC compilation, so we can get the specific enabled extensions from the `DynFlags` in the `ModSummary` for the file being changed. So being able to pass them in each time would work fine.

**Comment by lspitzner** [comment]
@alanz yeah something in that direction would be nicer. Just enabling extensions by default in the plugin is an acceptable workaround for now though, imo.
