### ISSUE TITLE
Consider adding `--inplace` option

### ISSUE THREAD

**Issue by fmthoma** [lspitzner/brittany#40]
Usage:
```
brittany --inplace **/*.hs
```

And since input files can already be specified as positional arguments, the `-i` parameter could be reassigned as shortcut for `--inplace`...

(My current workaround: `ls **/*.hs | xargs -I{} brittany -i {} -o {}`)

**Comment by lspitzner** [comment]
good point.

thinking aloud a bit:
- With your example, brittany would of course need to accept `[FILE..]` and not just `[FILE]`, so just quickly aliasing `--inplace x` to `--input x --output x` is not sufficient. (A great reason for me to refactor [the monstrosity that is the effective `main` function](https://github.com/lspitzner/brittany/blob/master/src-brittany/Main.hs#L130-L255). *whistles innocently*)
- We probably want abort on a per-file basis (syntax error in one file -> all other are still processed).
- Might want error/warning output to be prefixed with the current file, or just print "processing $FILE" for each one in order.
- Might want parallelization.

**Comment by lspitzner** [comment]
PR #59 adds an `--inplace` flag, but due to limitations of the `butcher` library the `brittany --inplace **/*.hs` usecase does not work yet. I'll fix that in `butcher` next.

**Comment by lspitzner** [comment]
I have uploaded `butcher-1.1.1.0` which has `addStringParams`.

@d-dorazio you wanna do the final bit to fix this?

**Comment by d-dorazio** [comment]
@lspitzner sure, but I also have a proposal: specifying input files both with `-i` and as parameters seem a bit verbose to me so I'd remove both `-i` and `-o` and provide an interface similar to what other formatters provide like [`rustfmt`](https://github.com/rust-lang-nursery/rustfmt#running). For example we could add `--write-mode inplace|display` and the files would be specified only as parameters.

**Comment by lspitzner** [comment]
@d-dorazio I agree, the current handling of `--input` vs param(s) can be improved, and `write-mode` makes sense. I don't see the verbosity argument - it only affects the (commandline) docs, but I have no strong opinion on this.

For clarification:

no | --inputs | --outputs | params | behaviour
|-|-|-|-|-
0 | \- | \- | \- | stdin to stdout
1 | \- | \- | params | inplace or according to `--write-mode`
2 | ifile | \- | \- | ifile to stdout
3 | \- | ofile | \- | stdin to ofile
4 | ifile | ofile | \- | ifile to ofile
5 | ifiles | ofiles | \- | if lengths match, act like `zipWithM`
6 | ifiles | ofiles | params | ?

Strongly in favour of 0 and 1, even if 1 is a breaking change due to implying `--inplace`. Slightly in favour of keeping support for 2/3/4. I can do without 5 and 6 (i.e. make param(s) and `-i`/`-o` incompatible).

There is one other related item: Do we want to support `brittany Foo.hs Bar.hs --flagA --flagB` ? And if not, warn about interpreting `--flagA` as a file name? The best solution probably is to stop supporting file names start with a dash and then allow reordering for params as well. I'll have to make another `butcher` release for that, whoops. That's what I get for not using `optparse-applicative` :D

**Comment by d-dorazio** [comment]
@lspitzner 1 and 2 look unintuitive to me, because I see `params` as basically equivalent to `--inputs`. I think that an interface like the following would be simpler and wouldn't provide ambiguities:

```shell
# stdin to stdout
$ brittany

# overwrite Main.hs
$ brittany --write-mode overwrite Main.hs

# files to stdout
$ brittany Main.hs src/Lib.hs

# overwrite all the files
$ brittany --write-mode overwrite Main.hs src/Lib.hs
```

It's true that you'd lose the ability to specify different output files than the input. I think it doesn't happen very often and you can always just redirect the output to the custom output.

If you feel strongly about it then I can implement it the other way though.

**Comment by lspitzner** [comment]
@d-dorazio what ambiguities? what you suggest there is farther from the `rustfmt` behaviour as you make `--write-mode display` the default; not that i am strictly opposed to this, but it seems to be the only difference between what our suggestions.
