### ISSUE TITLE
haskell-ide-engine integration

### ISSUE THREAD

**Issue by jacereda** [lspitzner/brittany#5]
Just an idea, would be cool if there was a haskell-ide-engine plugin for this. That way, all the editors integrating with hie could benefit from this project.

**Comment by wz1000** [comment]
@lspitzner This is closed by haskell/haskell-ide-engine/pull/247

**Comment by lspitzner** [comment]
neat! I trust this works, but i'll leave it open as a reminder for me to try it out. Curious if it already can replace my hand-configured editor integration that i currently use.

**Comment by wz1000** [comment]
It can via LSP (if your editor supports it). HIE also brings in integration
of other stuff like hlint refactorings, HaRe and ghcmod, and there is no
way of disabling theses in HIE itself, so it will essentially take over
your editors Haskell mode unless you configure it's lsp backend to only
handle the requests you need(hie uses Brittany to handle
textDocument/formatting and textDocument/rangeFormatting).

On 17-Jun-2017 18:57, "Lennart Spitzner" <notifications@github.com> wrote:

neat! I trust this works, but i'll leave it open as a reminder for me to
try it out. Curious if it already can replace my hand-configured editor
integration that i currently use.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/lspitzner/brittany/issues/5#issuecomment-309215124>,
or mute
the thread
